### ISSUE TITLE
altitude, mean sea level, please add

### ISSUE THREAD

**Issue by paulle** [nhirokinet/bluesquarespeedometer#26]
Please can you add showing the altitude in msl too?
Thank you for this nice app.

**Comment by nhirokinet** [comment]
No, as of 0.1.4, it was altitude based on WGS84.

By #45, it will show MSL altitude if it is available by new API added in Android SDK 34 (Android 14). WGS84 altitude will show as reference in this case. In Android <=13 it will stilll show WGS84 altitude.

And for both case, by this pull request, caption will clarify which altitude is shown.

**Comment by nhirokinet** [comment]
Added release tag and uploaded to Google Play.
It will take a bit more before it is available in Google Play and F-Droid according their policy/method.
